/*
    *
    * DiskCryptor - open source partition encryption tool
    * Copyright (c) 2007-2008 
    * ntldr <ntldr@freed0m.org> PGP key ID - 0xC48251EB4F8E4E6E
    *

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#include "defines.h"
#ifdef DEBUG

#include <ntifs.h>
#include <poclass.h>
#include <ntddchgr.h>
#include <ntddcdrm.h>
#include <ntddstor.h>
#include <ntdddisk.h>
#include <hidport.h>
#include <parallel.h>
#include <ntddtape.h>
#include <1394.h>
#include <61883.h>
#include <Ntddcdvd.h>
#include <usbscan.h>
#include <acpiioct.h>
#include <ntddscsi.h>
#include <ntddbeep.h>
#include <ntddmodm.h>
#include <Usbioctl.h>
#include <hidclass.h>
#include <ntddpcm.h>
#include <ntddpar.h>
#include <ntdd1394.h>
#include <bthdef.h>
#include <BthDdi.h>
#include <bthioctl.h>
#include <ntddmou.h>
#include <ntddkbd.h>
#include <ntdd8042.h>
#include <ntddser.h>
#include <ndis.h>
#include <ipfirewall.h>
#include <irclass_ioctl.h>
#include <mountmgr.h>
#include <mountdev.h>
#include <Pfhook.h>
#include <scsiscan.h>
#include <sffdisk.h>
#include <ntddtdi.h>
#include <Ntddvdeo.h>
#include <tdi.h>
#include <tdikrnl.h>
#include <tdiinfo.h>
#include <ntddvol.h>
#include <usbprint.h>
#include <usb.h>
#include <Usbuser.h>
#include "defines.h"



static struct {
	u32 code;
	s8 *name;
} ioctl_table[] = {
	{ IOCTL_1394_CLASS, "IOCTL_1394_CLASS" },
	{ IOCTL_1394_TOGGLE_ENUM_TEST_OFF, "IOCTL_1394_TOGGLE_ENUM_TEST_OFF" },
	{ IOCTL_1394_TOGGLE_ENUM_TEST_ON, "IOCTL_1394_TOGGLE_ENUM_TEST_ON" },
	{ IOCTL_61883_CLASS, "IOCTL_61883_CLASS" },
	{ IOCTL_AACS_END_SESSION, "IOCTL_AACS_END_SESSION" },
	{ IOCTL_AACS_GENERATE_BINDING_NONCE, "IOCTL_AACS_GENERATE_BINDING_NONCE" },
	{ IOCTL_AACS_GET_CERTIFICATE, "IOCTL_AACS_GET_CERTIFICATE" },
	{ IOCTL_AACS_GET_CHALLENGE_KEY, "IOCTL_AACS_GET_CHALLENGE_KEY" },
	{ IOCTL_AACS_READ_BINDING_NONCE, "IOCTL_AACS_READ_BINDING_NONCE" },
	{ IOCTL_AACS_READ_MEDIA_ID, "IOCTL_AACS_READ_MEDIA_ID" },
	{ IOCTL_AACS_READ_MEDIA_KEY_BLOCK, "IOCTL_AACS_READ_MEDIA_KEY_BLOCK" },
	{ IOCTL_AACS_READ_MEDIA_KEY_BLOCK_SIZE, "IOCTL_AACS_READ_MEDIA_KEY_BLOCK_SIZE" },
	{ IOCTL_AACS_READ_SERIAL_NUMBER, "IOCTL_AACS_READ_SERIAL_NUMBER" },
	{ IOCTL_AACS_READ_VOLUME_ID, "IOCTL_AACS_READ_VOLUME_ID" },
	{ IOCTL_AACS_SEND_CERTIFICATE, "IOCTL_AACS_SEND_CERTIFICATE" },
	{ IOCTL_AACS_SEND_CHALLENGE_KEY, "IOCTL_AACS_SEND_CHALLENGE_KEY" },
	{ IOCTL_AACS_START_SESSION, "IOCTL_AACS_START_SESSION" },
	{ IOCTL_ABORT_PIPE, "IOCTL_ABORT_PIPE" },
	{ IOCTL_ACPI_ACQUIRE_GLOBAL_LOCK, "IOCTL_ACPI_ACQUIRE_GLOBAL_LOCK" },
	{ IOCTL_ACPI_ASYNC_EVAL_METHOD, "IOCTL_ACPI_ASYNC_EVAL_METHOD" },
	{ IOCTL_ACPI_ASYNC_EVAL_METHOD_EX, "IOCTL_ACPI_ASYNC_EVAL_METHOD_EX" },
	{ IOCTL_ACPI_ENUM_CHILDREN, "IOCTL_ACPI_ENUM_CHILDREN" },
	{ IOCTL_ACPI_EVAL_METHOD, "IOCTL_ACPI_EVAL_METHOD" },
	{ IOCTL_ACPI_EVAL_METHOD_EX, "IOCTL_ACPI_EVAL_METHOD_EX" },
	{ IOCTL_ACPI_RELEASE_GLOBAL_LOCK, "IOCTL_ACPI_RELEASE_GLOBAL_LOCK" },
	{ IOCTL_ATA_MINIPORT, "IOCTL_ATA_MINIPORT" },
	{ IOCTL_ATA_PASS_THROUGH, "IOCTL_ATA_PASS_THROUGH" },
	{ IOCTL_ATA_PASS_THROUGH_DIRECT, "IOCTL_ATA_PASS_THROUGH_DIRECT" },
	{ IOCTL_BATTERY_QUERY_INFORMATION, "IOCTL_BATTERY_QUERY_INFORMATION" },
	{ IOCTL_BATTERY_QUERY_STATUS, "IOCTL_BATTERY_QUERY_STATUS" },
	{ IOCTL_BATTERY_QUERY_TAG, "IOCTL_BATTERY_QUERY_TAG" },
	{ IOCTL_BATTERY_SET_INFORMATION, "IOCTL_BATTERY_SET_INFORMATION" },
	{ IOCTL_BEEP_SET, "IOCTL_BEEP_SET" },
    { IOCTL_CANCEL_GET_SEND_MESSAGE, "IOCTL_CANCEL_GET_SEND_MESSAGE" },
	{ IOCTL_CANCEL_IO, "IOCTL_CANCEL_IO" },
	{ IOCTL_CDROM_BASE, "IOCTL_CDROM_BASE" },
	{ IOCTL_CDROM_CHECK_VERIFY, "IOCTL_CDROM_CHECK_VERIFY" },
	{ IOCTL_CDROM_CURRENT_POSITION, "IOCTL_CDROM_CURRENT_POSITION" },
	{ IOCTL_CDROM_DISK_TYPE, "IOCTL_CDROM_DISK_TYPE" },
	{ IOCTL_CDROM_EJECT_MEDIA, "IOCTL_CDROM_EJECT_MEDIA" },
	{ IOCTL_CDROM_EXCLUSIVE_ACCESS, "IOCTL_CDROM_EXCLUSIVE_ACCESS" },
	{ IOCTL_CDROM_FIND_NEW_DEVICES, "IOCTL_CDROM_FIND_NEW_DEVICES" },
	{ IOCTL_CDROM_GET_CONFIGURATION, "IOCTL_CDROM_GET_CONFIGURATION" },
	{ IOCTL_CDROM_GET_DRIVE_GEOMETRY, "IOCTL_CDROM_GET_DRIVE_GEOMETRY" },
	{ IOCTL_CDROM_GET_DRIVE_GEOMETRY_EX, "IOCTL_CDROM_GET_DRIVE_GEOMETRY_EX" },
	{ IOCTL_CDROM_GET_INQUIRY_DATA, "IOCTL_CDROM_GET_INQUIRY_DATA" },
	{ IOCTL_CDROM_GET_LAST_SESSION, "IOCTL_CDROM_GET_LAST_SESSION" },
	{ IOCTL_CDROM_GET_VOLUME, "IOCTL_CDROM_GET_VOLUME" },
	{ IOCTL_CDROM_LOAD_MEDIA, "IOCTL_CDROM_LOAD_MEDIA" },
	{ IOCTL_CDROM_MEDIA_CATALOG, "IOCTL_CDROM_MEDIA_CATALOG" },
	{ IOCTL_CDROM_MEDIA_REMOVAL, "IOCTL_CDROM_MEDIA_REMOVAL" },
	{ IOCTL_CDROM_PAUSE_AUDIO, "IOCTL_CDROM_PAUSE_AUDIO" },
	{ IOCTL_CDROM_PLAY_AUDIO_MSF, "IOCTL_CDROM_PLAY_AUDIO_MSF" },
	{ IOCTL_CDROM_RAW_READ, "IOCTL_CDROM_RAW_READ" },
	{ IOCTL_CDROM_READ_Q_CHANNEL, "IOCTL_CDROM_READ_Q_CHANNEL" },
	{ IOCTL_CDROM_READ_TOC, "IOCTL_CDROM_READ_TOC" },
	{ IOCTL_CDROM_READ_TOC_EX, "IOCTL_CDROM_READ_TOC_EX" },
	{ IOCTL_CDROM_RELEASE, "IOCTL_CDROM_RELEASE" },
	{ IOCTL_CDROM_RESERVE, "IOCTL_CDROM_RESERVE" },
	{ IOCTL_CDROM_RESUME_AUDIO, "IOCTL_CDROM_RESUME_AUDIO" },
	{ IOCTL_CDROM_SEEK_AUDIO_MSF, "IOCTL_CDROM_SEEK_AUDIO_MSF" },
	{ IOCTL_CDROM_SET_SPEED, "IOCTL_CDROM_SET_SPEED" },
	{ IOCTL_CDROM_SET_VOLUME, "IOCTL_CDROM_SET_VOLUME" },
	{ IOCTL_CDROM_SIMBAD, "IOCTL_CDROM_SIMBAD" },
	{ IOCTL_CDROM_STOP_AUDIO, "IOCTL_CDROM_STOP_AUDIO" },
	{ IOCTL_CDROM_SUB_Q_CHANNEL, "IOCTL_CDROM_SUB_Q_CHANNEL" },
	{ IOCTL_CDROM_TRACK_ISRC, "IOCTL_CDROM_TRACK_ISRC" },
	{ IOCTL_CDROM_UNLOAD_DRIVER, "IOCTL_CDROM_UNLOAD_DRIVER" },
	{ IOCTL_CHANGER_BASE, "IOCTL_CHANGER_BASE" },
	{ IOCTL_CHANGER_EXCHANGE_MEDIUM, "IOCTL_CHANGER_EXCHANGE_MEDIUM" },
	{ IOCTL_CHANGER_GET_ELEMENT_STATUS, "IOCTL_CHANGER_GET_ELEMENT_STATUS" },
	{ IOCTL_CHANGER_GET_PARAMETERS, "IOCTL_CHANGER_GET_PARAMETERS" },
	{ IOCTL_CHANGER_GET_PRODUCT_DATA, "IOCTL_CHANGER_GET_PRODUCT_DATA" },
	{ IOCTL_CHANGER_GET_STATUS, "IOCTL_CHANGER_GET_STATUS" },
	{ IOCTL_CHANGER_INITIALIZE_ELEMENT_STATUS, "IOCTL_CHANGER_INITIALIZE_ELEMENT_STATUS" },
	{ IOCTL_CHANGER_MOVE_MEDIUM, "IOCTL_CHANGER_MOVE_MEDIUM" },
	{ IOCTL_CHANGER_QUERY_VOLUME_TAGS, "IOCTL_CHANGER_QUERY_VOLUME_TAGS" },
	{ IOCTL_CHANGER_REINITIALIZE_TRANSPORT, "IOCTL_CHANGER_REINITIALIZE_TRANSPORT" },
	{ IOCTL_CHANGER_SET_ACCESS, "IOCTL_CHANGER_SET_ACCESS" },
	{ IOCTL_CHANGER_SET_POSITION, "IOCTL_CHANGER_SET_POSITION" },
	{ IOCTL_DISK_BASE, "IOCTL_DISK_BASE" },
	{ IOCTL_DISK_CHECK_VERIFY, "IOCTL_DISK_CHECK_VERIFY" },
	{ IOCTL_DISK_CONTROLLER_NUMBER, "IOCTL_DISK_CONTROLLER_NUMBER" },
	{ IOCTL_DISK_COPY_DATA, "IOCTL_DISK_COPY_DATA" },
	{ IOCTL_DISK_CREATE_DISK, "IOCTL_DISK_CREATE_DISK" },
	{ IOCTL_DISK_DELETE_DRIVE_LAYOUT, "IOCTL_DISK_DELETE_DRIVE_LAYOUT" },
	{ IOCTL_DISK_EJECT_MEDIA, "IOCTL_DISK_EJECT_MEDIA" },
	{ IOCTL_DISK_FIND_NEW_DEVICES, "IOCTL_DISK_FIND_NEW_DEVICES" },
	{ IOCTL_DISK_FORMAT_DRIVE, "IOCTL_DISK_FORMAT_DRIVE" },
	{ IOCTL_DISK_FORMAT_TRACKS, "IOCTL_DISK_FORMAT_TRACKS" },
	{ IOCTL_DISK_FORMAT_TRACKS_EX, "IOCTL_DISK_FORMAT_TRACKS_EX" },
	{ IOCTL_DISK_GET_CACHE_INFORMATION, "IOCTL_DISK_GET_CACHE_INFORMATION" },
	{ IOCTL_DISK_GET_CACHE_SETTING, "IOCTL_DISK_GET_CACHE_SETTING" },
	{ IOCTL_DISK_GET_DRIVE_GEOMETRY, "IOCTL_DISK_GET_DRIVE_GEOMETRY" },
	{ IOCTL_DISK_GET_DRIVE_GEOMETRY_EX, "IOCTL_DISK_GET_DRIVE_GEOMETRY_EX" },
	{ IOCTL_DISK_GET_DRIVE_LAYOUT, "IOCTL_DISK_GET_DRIVE_LAYOUT" },
	{ IOCTL_DISK_GET_DRIVE_LAYOUT_EX, "IOCTL_DISK_GET_DRIVE_LAYOUT_EX" },
	{ IOCTL_DISK_GET_LENGTH_INFO, "IOCTL_DISK_GET_LENGTH_INFO" },
	{ IOCTL_DISK_GET_MEDIA_TYPES, "IOCTL_DISK_GET_MEDIA_TYPES" },
	{ IOCTL_DISK_GET_PARTITION_INFO, "IOCTL_DISK_GET_PARTITION_INFO" },
	{ IOCTL_DISK_GET_PARTITION_INFO_EX, "IOCTL_DISK_GET_PARTITION_INFO_EX" },
	{ IOCTL_DISK_GROW_PARTITION, "IOCTL_DISK_GROW_PARTITION" },
	{ IOCTL_DISK_HISTOGRAM_DATA, "IOCTL_DISK_HISTOGRAM_DATA" },
	{ IOCTL_DISK_HISTOGRAM_RESET, "IOCTL_DISK_HISTOGRAM_RESET" },
	{ IOCTL_DISK_HISTOGRAM_STRUCTURE, "IOCTL_DISK_HISTOGRAM_STRUCTURE" },
	{ IOCTL_DISK_INTERNAL_CLEAR_VERIFY, "IOCTL_DISK_INTERNAL_CLEAR_VERIFY" },
	{ IOCTL_DISK_INTERNAL_SET_NOTIFY, "IOCTL_DISK_INTERNAL_SET_NOTIFY" },
	{ IOCTL_DISK_INTERNAL_SET_VERIFY, "IOCTL_DISK_INTERNAL_SET_VERIFY" },
	{ IOCTL_DISK_IS_WRITABLE, "IOCTL_DISK_IS_WRITABLE" },
	{ IOCTL_DISK_LOAD_MEDIA, "IOCTL_DISK_LOAD_MEDIA" },
	{ IOCTL_DISK_LOGGING, "IOCTL_DISK_LOGGING" },
	{ IOCTL_DISK_MEDIA_REMOVAL, "IOCTL_DISK_MEDIA_REMOVAL" },
	{ IOCTL_DISK_PERFORMANCE, "IOCTL_DISK_PERFORMANCE" },
	{ IOCTL_DISK_PERFORMANCE_OFF, "IOCTL_DISK_PERFORMANCE_OFF" },
	{ IOCTL_DISK_REASSIGN_BLOCKS, "IOCTL_DISK_REASSIGN_BLOCKS" },
	{ IOCTL_DISK_REASSIGN_BLOCKS_EX, "IOCTL_DISK_REASSIGN_BLOCKS_EX" },
	{ IOCTL_DISK_RELEASE, "IOCTL_DISK_RELEASE" },
	{ IOCTL_DISK_REQUEST_DATA, "IOCTL_DISK_REQUEST_DATA" },
	{ IOCTL_DISK_REQUEST_STRUCTURE, "IOCTL_DISK_REQUEST_STRUCTURE" },
	{ IOCTL_DISK_RESERVE, "IOCTL_DISK_RESERVE" },
	{ IOCTL_DISK_SENSE_DEVICE, "IOCTL_DISK_SENSE_DEVICE" },
	{ IOCTL_DISK_SET_CACHE_INFORMATION, "IOCTL_DISK_SET_CACHE_INFORMATION" },
	{ IOCTL_DISK_SET_CACHE_SETTING, "IOCTL_DISK_SET_CACHE_SETTING" },
	{ IOCTL_DISK_SET_DRIVE_LAYOUT, "IOCTL_DISK_SET_DRIVE_LAYOUT" },
	{ IOCTL_DISK_SET_DRIVE_LAYOUT_EX, "IOCTL_DISK_SET_DRIVE_LAYOUT_EX" },
	{ IOCTL_DISK_SET_PARTITION_INFO, "IOCTL_DISK_SET_PARTITION_INFO" },
	{ IOCTL_DISK_SET_PARTITION_INFO_EX, "IOCTL_DISK_SET_PARTITION_INFO_EX" },
	{ IOCTL_DISK_UPDATE_DRIVE_SIZE, "IOCTL_DISK_UPDATE_DRIVE_SIZE" },
	{ IOCTL_DISK_UPDATE_PROPERTIES, "IOCTL_DISK_UPDATE_PROPERTIES" },
	{ IOCTL_DISK_VERIFY, "IOCTL_DISK_VERIFY" },
	{ IOCTL_DVD_BASE, "IOCTL_DVD_BASE" },
	{ IOCTL_DVD_END_SESSION, "IOCTL_DVD_END_SESSION" },
	{ IOCTL_DVD_GET_REGION, "IOCTL_DVD_GET_REGION" },
	{ IOCTL_DVD_READ_KEY, "IOCTL_DVD_READ_KEY" },
	{ IOCTL_DVD_READ_STRUCTURE, "IOCTL_DVD_READ_STRUCTURE" },
	{ IOCTL_DVD_SEND_KEY, "IOCTL_DVD_SEND_KEY" },
	{ IOCTL_DVD_SEND_KEY2, "IOCTL_DVD_SEND_KEY2" },
	{ IOCTL_DVD_SET_READ_AHEAD, "IOCTL_DVD_SET_READ_AHEAD" },
	{ IOCTL_DVD_START_SESSION, "IOCTL_DVD_START_SESSION" },
	{ IOCTL_GET_CHANNEL_ALIGN_RQST, "IOCTL_GET_CHANNEL_ALIGN_RQST" },
	{ IOCTL_GET_DEVICE_DESCRIPTOR, "IOCTL_GET_DEVICE_DESCRIPTOR" },
	{ IOCTL_GET_HCD_DRIVERKEY_NAME, "IOCTL_GET_HCD_DRIVERKEY_NAME" },
	{ IOCTL_GET_NUM_DEVICE_INPUT_BUFFERS, "IOCTL_GET_NUM_DEVICE_INPUT_BUFFERS" },
	{ IOCTL_GET_PHYSICAL_DESCRIPTOR, "IOCTL_GET_PHYSICAL_DESCRIPTOR" },
	{ IOCTL_GET_PIPE_CONFIGURATION, "IOCTL_GET_PIPE_CONFIGURATION" },
	{ IOCTL_GET_PROCESSOR_OBJ_INFO, "IOCTL_GET_PROCESSOR_OBJ_INFO" },
	{ IOCTL_GET_SYS_BUTTON_CAPS, "IOCTL_GET_SYS_BUTTON_CAPS" },
	{ IOCTL_GET_SYS_BUTTON_EVENT, "IOCTL_GET_SYS_BUTTON_EVENT" },
	{ IOCTL_GET_TUPLE_DATA, "IOCTL_GET_TUPLE_DATA" },
	{ IOCTL_GET_USB_DESCRIPTOR, "IOCTL_GET_USB_DESCRIPTOR" },
	{ IOCTL_GET_VERSION, "IOCTL_GET_VERSION" },
	{ IOCTL_HID_ACTIVATE_DEVICE, "IOCTL_HID_ACTIVATE_DEVICE" },
	{ IOCTL_HID_DEACTIVATE_DEVICE, "IOCTL_HID_DEACTIVATE_DEVICE" },
	{ IOCTL_HID_ENABLE_SECURE_READ, "IOCTL_HID_ENABLE_SECURE_READ" },
	{ IOCTL_HID_FLUSH_QUEUE, "IOCTL_HID_FLUSH_QUEUE" },
	{ IOCTL_HID_GET_COLLECTION_DESCRIPTOR, "IOCTL_HID_GET_COLLECTION_DESCRIPTOR" },
	{ IOCTL_HID_GET_COLLECTION_INFORMATION, "IOCTL_HID_GET_COLLECTION_INFORMATION" },
	{ IOCTL_HID_GET_DEVICE_ATTRIBUTES, "IOCTL_HID_GET_DEVICE_ATTRIBUTES" },
	{ IOCTL_HID_GET_DEVICE_DESCRIPTOR, "IOCTL_HID_GET_DEVICE_DESCRIPTOR" },
	{ IOCTL_HID_GET_DRIVER_CONFIG, "IOCTL_HID_GET_DRIVER_CONFIG" },
	{ IOCTL_HID_GET_FEATURE, "IOCTL_HID_GET_FEATURE" },
	{ IOCTL_HID_GET_HARDWARE_ID, "IOCTL_HID_GET_HARDWARE_ID" },
	{ IOCTL_HID_GET_INDEXED_STRING, "IOCTL_HID_GET_INDEXED_STRING" },
	{ IOCTL_HID_GET_INPUT_REPORT, "IOCTL_HID_GET_INPUT_REPORT" },
	{ IOCTL_HID_GET_MANUFACTURER_STRING, "IOCTL_HID_GET_MANUFACTURER_STRING" },
	{ IOCTL_HID_GET_MS_GENRE_DESCRIPTOR, "IOCTL_HID_GET_MS_GENRE_DESCRIPTOR" },
	{ IOCTL_HID_GET_POLL_FREQUENCY_MSEC, "IOCTL_HID_GET_POLL_FREQUENCY_MSEC" },
	{ IOCTL_HID_GET_PRODUCT_STRING, "IOCTL_HID_GET_PRODUCT_STRING" },
	{ IOCTL_HID_GET_REPORT_DESCRIPTOR, "IOCTL_HID_GET_REPORT_DESCRIPTOR" },
	{ IOCTL_HID_GET_SERIALNUMBER_STRING, "IOCTL_HID_GET_SERIALNUMBER_STRING" },
	{ IOCTL_HID_GET_STRING, "IOCTL_HID_GET_STRING" },
	{ IOCTL_HID_READ_REPORT, "IOCTL_HID_READ_REPORT" },
	{ IOCTL_HID_SEND_IDLE_NOTIFICATION_REQUEST, "IOCTL_HID_SEND_IDLE_NOTIFICATION_REQUEST" },
	{ IOCTL_HID_SET_DRIVER_CONFIG, "IOCTL_HID_SET_DRIVER_CONFIG" },
	{ IOCTL_HID_SET_FEATURE, "IOCTL_HID_SET_FEATURE" },
	{ IOCTL_HID_SET_OUTPUT_REPORT, "IOCTL_HID_SET_OUTPUT_REPORT" },
	{ IOCTL_HID_SET_POLL_FREQUENCY_MSEC, "IOCTL_HID_SET_POLL_FREQUENCY_MSEC" },
	{ IOCTL_HID_WRITE_REPORT, "IOCTL_HID_WRITE_REPORT" },
	{ IOCTL_IDE_PASS_THROUGH, "IOCTL_IDE_PASS_THROUGH" },
	{ IOCTL_IEEE1284_GET_MODE, "IOCTL_IEEE1284_GET_MODE" },
	{ IOCTL_IEEE1284_NEGOTIATE, "IOCTL_IEEE1284_NEGOTIATE" },
	{ IOCTL_IEEE1394_API_REQUEST, "IOCTL_IEEE1394_API_REQUEST" },
	{ IOCTL_INDEX, "IOCTL_INDEX" },
	{ IOCTL_INTERNAL_BTH_SUBMIT_BRB, "IOCTL_INTERNAL_BTH_SUBMIT_BRB" },
	{ IOCTL_INTERNAL_BTHENUM_GET_DEVINFO, "IOCTL_INTERNAL_BTHENUM_GET_DEVINFO" },
	{ IOCTL_INTERNAL_BTHENUM_GET_ENUMINFO, "IOCTL_INTERNAL_BTHENUM_GET_ENUMINFO" },
	{ IOCTL_INTERNAL_DISABLE_END_OF_CHAIN_BUS_RESCAN, "IOCTL_INTERNAL_DISABLE_END_OF_CHAIN_BUS_RESCAN" },
	{ IOCTL_INTERNAL_ENABLE_END_OF_CHAIN_BUS_RESCAN, "IOCTL_INTERNAL_ENABLE_END_OF_CHAIN_BUS_RESCAN" },
	{ IOCTL_INTERNAL_I8042_CONTROLLER_WRITE_BUFFER, "IOCTL_INTERNAL_I8042_CONTROLLER_WRITE_BUFFER" },
	{ IOCTL_INTERNAL_I8042_HOOK_KEYBOARD, "IOCTL_INTERNAL_I8042_HOOK_KEYBOARD" },
	{ IOCTL_INTERNAL_I8042_HOOK_MOUSE, "IOCTL_INTERNAL_I8042_HOOK_MOUSE" },
	{ IOCTL_INTERNAL_I8042_KEYBOARD_START_INFORMATION, "IOCTL_INTERNAL_I8042_KEYBOARD_START_INFORMATION" },
	{ IOCTL_INTERNAL_I8042_KEYBOARD_WRITE_BUFFER, "IOCTL_INTERNAL_I8042_KEYBOARD_WRITE_BUFFER" },
	{ IOCTL_INTERNAL_I8042_MOUSE_START_INFORMATION, "IOCTL_INTERNAL_I8042_MOUSE_START_INFORMATION" },
	{ IOCTL_INTERNAL_I8042_MOUSE_WRITE_BUFFER, "IOCTL_INTERNAL_I8042_MOUSE_WRITE_BUFFER" },
	{ IOCTL_INTERNAL_LOCK_PORT_NO_SELECT, "IOCTL_INTERNAL_LOCK_PORT_NO_SELECT" },
	{ IOCTL_INTERNAL_PARALLEL_PORT_FREE, "IOCTL_INTERNAL_PARALLEL_PORT_FREE" },
	{ IOCTL_INTERNAL_PARDOT3_CONNECT, "IOCTL_INTERNAL_PARDOT3_CONNECT" },
	{ IOCTL_INTERNAL_PARDOT3_DISCONNECT, "IOCTL_INTERNAL_PARDOT3_DISCONNECT" },
	{ IOCTL_INTERNAL_PARDOT3_RESET, "IOCTL_INTERNAL_PARDOT3_RESET" },
	{ IOCTL_INTERNAL_PARDOT3_SIGNAL, "IOCTL_INTERNAL_PARDOT3_SIGNAL" },
	{ IOCTL_INTERNAL_SERENUM_REMOVE_SELF, "IOCTL_INTERNAL_SERENUM_REMOVE_SELF" },
	{ IOCTL_INTERNAL_UNLOCK_PORT_NO_DESELECT, "IOCTL_INTERNAL_UNLOCK_PORT_NO_DESELECT" },
	{ IOCTL_INTERNAL_USB_ENABLE_PORT, "IOCTL_INTERNAL_USB_ENABLE_PORT" },
	{ IOCTL_INTERNAL_USB_GET_PORT_STATUS, "IOCTL_INTERNAL_USB_GET_PORT_STATUS" },
	{ IOCTL_INTERNAL_USB_GET_ROOTHUB_PDO, "IOCTL_INTERNAL_USB_GET_ROOTHUB_PDO" },
	{ IOCTL_INTERNAL_USB_RESET_PORT, "IOCTL_INTERNAL_USB_RESET_PORT" },
	{ IOCTL_INTERNAL_USB_SUBMIT_URB, "IOCTL_INTERNAL_USB_SUBMIT_URB" },
	//{ IOCTL_IP_SET_FIREWALL_HOOK, "IOCTL_IP_SET_FIREWALL_HOOK" },
	{ IOCTL_IR_ENTER_PRIORITY_RECEIVE, "IOCTL_IR_ENTER_PRIORITY_RECEIVE" },
	{ IOCTL_IR_EXIT_PRIORITY_RECEIVE, "IOCTL_IR_EXIT_PRIORITY_RECEIVE" },
	{ IOCTL_IR_FLASH_RECEIVER, "IOCTL_IR_FLASH_RECEIVER" },
	{ IOCTL_IR_GET_DEV_CAPS, "IOCTL_IR_GET_DEV_CAPS" },
	{ IOCTL_IR_GET_EMITTERS, "IOCTL_IR_GET_EMITTERS" },
	{ IOCTL_IR_HANDSHAKE, "IOCTL_IR_HANDSHAKE" },
	{ IOCTL_IR_PRIORITY_RECEIVE, "IOCTL_IR_PRIORITY_RECEIVE" },
	{ IOCTL_IR_RECEIVE, "IOCTL_IR_RECEIVE" },
	{ IOCTL_IR_RESET_DEVICE, "IOCTL_IR_RESET_DEVICE" },
	{ IOCTL_IR_TRANSMIT, "IOCTL_IR_TRANSMIT" },
	{ IOCTL_IR_USER_CLOSE, "IOCTL_IR_USER_CLOSE" },
	{ IOCTL_IR_USER_OPEN, "IOCTL_IR_USER_OPEN" },
	{ IOCTL_KEYBOARD_INSERT_DATA, "IOCTL_KEYBOARD_INSERT_DATA" },
	{ IOCTL_KEYBOARD_QUERY_ATTRIBUTES, "IOCTL_KEYBOARD_QUERY_ATTRIBUTES" },
	{ IOCTL_KEYBOARD_QUERY_IME_STATUS, "IOCTL_KEYBOARD_QUERY_IME_STATUS" },
	{ IOCTL_KEYBOARD_QUERY_INDICATOR_TRANSLATION, "IOCTL_KEYBOARD_QUERY_INDICATOR_TRANSLATION" },
	{ IOCTL_KEYBOARD_QUERY_INDICATORS, "IOCTL_KEYBOARD_QUERY_INDICATORS" },
	{ IOCTL_KEYBOARD_QUERY_TYPEMATIC, "IOCTL_KEYBOARD_QUERY_TYPEMATIC" },
	{ IOCTL_KEYBOARD_SET_IME_STATUS, "IOCTL_KEYBOARD_SET_IME_STATUS" },
	{ IOCTL_KEYBOARD_SET_INDICATORS, "IOCTL_KEYBOARD_SET_INDICATORS" },
	{ IOCTL_KEYBOARD_SET_TYPEMATIC, "IOCTL_KEYBOARD_SET_TYPEMATIC" },
	{ IOCTL_MODEM_CHECK_FOR_MODEM, "IOCTL_MODEM_CHECK_FOR_MODEM" },
	{ IOCTL_MODEM_GET_DLE, "IOCTL_MODEM_GET_DLE" },
	{ IOCTL_MODEM_GET_MESSAGE, "IOCTL_MODEM_GET_MESSAGE" },
	{ IOCTL_MODEM_GET_PASSTHROUGH, "IOCTL_MODEM_GET_PASSTHROUGH" },
	{ IOCTL_MODEM_SEND_GET_MESSAGE, "IOCTL_MODEM_SEND_GET_MESSAGE" },
	{ IOCTL_MODEM_SEND_LOOPBACK_MESSAGE, "IOCTL_MODEM_SEND_LOOPBACK_MESSAGE" },
	{ IOCTL_MODEM_SEND_MESSAGE, "IOCTL_MODEM_SEND_MESSAGE" },
	{ IOCTL_MODEM_SET_DLE_MONITORING, "IOCTL_MODEM_SET_DLE_MONITORING" },
	{ IOCTL_MODEM_SET_DLE_SHIELDING, "IOCTL_MODEM_SET_DLE_SHIELDING" },
	{ IOCTL_MODEM_SET_MIN_POWER, "IOCTL_MODEM_SET_MIN_POWER" },
	{ IOCTL_MODEM_SET_PASSTHROUGH, "IOCTL_MODEM_SET_PASSTHROUGH" },
	{ IOCTL_MODEM_STOP_WAVE_RECEIVE, "IOCTL_MODEM_STOP_WAVE_RECEIVE" },
	{ IOCTL_MODEM_WATCH_FOR_RESUME, "IOCTL_MODEM_WATCH_FOR_RESUME" },
	{ IOCTL_MOUNTDEV_LINK_CREATED, "IOCTL_MOUNTDEV_LINK_CREATED" },
	{ IOCTL_MOUNTDEV_LINK_DELETED, "IOCTL_MOUNTDEV_LINK_DELETED" },
	{ IOCTL_MOUNTDEV_QUERY_DEVICE_NAME, "IOCTL_MOUNTDEV_QUERY_DEVICE_NAME" },
	{ IOCTL_MOUNTDEV_QUERY_STABLE_GUID, "IOCTL_MOUNTDEV_QUERY_STABLE_GUID" },
	{ IOCTL_MOUNTDEV_QUERY_SUGGESTED_LINK_NAME, "IOCTL_MOUNTDEV_QUERY_SUGGESTED_LINK_NAME" },
	{ IOCTL_MOUNTDEV_QUERY_UNIQUE_ID, "IOCTL_MOUNTDEV_QUERY_UNIQUE_ID" },
	{ IOCTL_MOUNTDEV_UNIQUE_ID_CHANGE_NOTIFY, "IOCTL_MOUNTDEV_UNIQUE_ID_CHANGE_NOTIFY" },
	{ IOCTL_MOUNTMGR_AUTO_DL_ASSIGNMENTS, "IOCTL_MOUNTMGR_AUTO_DL_ASSIGNMENTS" },
	{ IOCTL_MOUNTMGR_CHANGE_NOTIFY, "IOCTL_MOUNTMGR_CHANGE_NOTIFY" },
	{ IOCTL_MOUNTMGR_CHECK_UNPROCESSED_VOLUMES, "IOCTL_MOUNTMGR_CHECK_UNPROCESSED_VOLUMES" },
	{ IOCTL_MOUNTMGR_CREATE_POINT, "IOCTL_MOUNTMGR_CREATE_POINT" },
	{ IOCTL_MOUNTMGR_DELETE_POINTS, "IOCTL_MOUNTMGR_DELETE_POINTS" },
	{ IOCTL_MOUNTMGR_DELETE_POINTS_DBONLY, "IOCTL_MOUNTMGR_DELETE_POINTS_DBONLY" },
	{ IOCTL_MOUNTMGR_KEEP_LINKS_WHEN_OFFLINE, "IOCTL_MOUNTMGR_KEEP_LINKS_WHEN_OFFLINE" },
	{ IOCTL_MOUNTMGR_NEXT_DRIVE_LETTER, "IOCTL_MOUNTMGR_NEXT_DRIVE_LETTER" },
	{ IOCTL_MOUNTMGR_QUERY_AUTO_MOUNT, "IOCTL_MOUNTMGR_QUERY_AUTO_MOUNT" },
	{ IOCTL_MOUNTMGR_QUERY_DOS_VOLUME_PATH, "IOCTL_MOUNTMGR_QUERY_DOS_VOLUME_PATH" },
	{ IOCTL_MOUNTMGR_QUERY_DOS_VOLUME_PATHS, "IOCTL_MOUNTMGR_QUERY_DOS_VOLUME_PATHS" },
	{ IOCTL_MOUNTMGR_QUERY_POINTS, "IOCTL_MOUNTMGR_QUERY_POINTS" },
	{ IOCTL_MOUNTMGR_SCRUB_REGISTRY, "IOCTL_MOUNTMGR_SCRUB_REGISTRY" },
	{ IOCTL_MOUNTMGR_SET_AUTO_MOUNT, "IOCTL_MOUNTMGR_SET_AUTO_MOUNT" },
	{ IOCTL_MOUNTMGR_VOLUME_ARRIVAL_NOTIFICATION, "IOCTL_MOUNTMGR_VOLUME_ARRIVAL_NOTIFICATION" },
	{ IOCTL_MOUNTMGR_VOLUME_MOUNT_POINT_CREATED, "IOCTL_MOUNTMGR_VOLUME_MOUNT_POINT_CREATED" },
	{ IOCTL_MOUNTMGR_VOLUME_MOUNT_POINT_DELETED, "IOCTL_MOUNTMGR_VOLUME_MOUNT_POINT_DELETED" },
	{ IOCTL_MOUSE_INSERT_DATA, "IOCTL_MOUSE_INSERT_DATA" },
	{ IOCTL_MOUSE_QUERY_ATTRIBUTES, "IOCTL_MOUSE_QUERY_ATTRIBUTES" },
	{ IOCTL_NDIS_ADD_TDI_DEVICE, "IOCTL_NDIS_ADD_TDI_DEVICE" },
	{ IOCTL_NDIS_DO_PNP_OPERATION, "IOCTL_NDIS_DO_PNP_OPERATION" },
	{ IOCTL_NDIS_ENUMERATE_INTERFACES, "IOCTL_NDIS_ENUMERATE_INTERFACES" },
	{ IOCTL_NDIS_GET_LOG_DATA, "IOCTL_NDIS_GET_LOG_DATA" },
	{ IOCTL_NDIS_GET_VERSION, "IOCTL_NDIS_GET_VERSION" },
	{ IOCTL_NDIS_QUERY_ALL_STATS, "IOCTL_NDIS_QUERY_ALL_STATS" },
	{ IOCTL_NDIS_QUERY_GLOBAL_STATS, "IOCTL_NDIS_QUERY_GLOBAL_STATS" },
	{ IOCTL_NDIS_QUERY_SELECTED_STATS, "IOCTL_NDIS_QUERY_SELECTED_STATS" },
	{ IOCTL_NDIS_RESERVED1, "IOCTL_NDIS_RESERVED1" },
	{ IOCTL_NDIS_RESERVED10, "IOCTL_NDIS_RESERVED10" },
	{ IOCTL_NDIS_RESERVED11, "IOCTL_NDIS_RESERVED11" },
	{ IOCTL_NDIS_RESERVED12, "IOCTL_NDIS_RESERVED12" },
	{ IOCTL_NDIS_RESERVED13, "IOCTL_NDIS_RESERVED13" },
	{ IOCTL_NDIS_RESERVED2, "IOCTL_NDIS_RESERVED2" },
	{ IOCTL_NDIS_RESERVED3, "IOCTL_NDIS_RESERVED3" },
	{ IOCTL_NDIS_RESERVED4, "IOCTL_NDIS_RESERVED4" },
	{ IOCTL_NDIS_RESERVED5, "IOCTL_NDIS_RESERVED5" },
	{ IOCTL_NDIS_RESERVED6, "IOCTL_NDIS_RESERVED6" },
	{ IOCTL_NDIS_RESERVED7, "IOCTL_NDIS_RESERVED7" },
	{ IOCTL_NDIS_RESERVED8, "IOCTL_NDIS_RESERVED8" },
	{ IOCTL_NDIS_RESERVED9, "IOCTL_NDIS_RESERVED9" },
	{ IOCTL_PAR_BASE, "IOCTL_PAR_BASE" },
	{ IOCTL_PAR_ECP_HOST_RECOVERY, "IOCTL_PAR_ECP_HOST_RECOVERY" },
	{ IOCTL_PAR_GET_DEFAULT_MODES, "IOCTL_PAR_GET_DEFAULT_MODES" },
	{ IOCTL_PAR_GET_DEVICE_CAPS, "IOCTL_PAR_GET_DEVICE_CAPS" },
	{ IOCTL_PAR_GET_READ_ADDRESS, "IOCTL_PAR_GET_READ_ADDRESS" },
	{ IOCTL_PAR_GET_WRITE_ADDRESS, "IOCTL_PAR_GET_WRITE_ADDRESS" },
	{ IOCTL_PAR_IS_PORT_FREE, "IOCTL_PAR_IS_PORT_FREE" },
	{ IOCTL_PAR_PING, "IOCTL_PAR_PING" },
	{ IOCTL_PAR_QUERY_DEVICE_ID, "IOCTL_PAR_QUERY_DEVICE_ID" },
	{ IOCTL_PAR_QUERY_DEVICE_ID_SIZE, "IOCTL_PAR_QUERY_DEVICE_ID_SIZE" },
	{ IOCTL_PAR_QUERY_INFORMATION, "IOCTL_PAR_QUERY_INFORMATION" },
	{ IOCTL_PAR_QUERY_LOCATION, "IOCTL_PAR_QUERY_LOCATION" },
	{ IOCTL_PAR_QUERY_RAW_DEVICE_ID, "IOCTL_PAR_QUERY_RAW_DEVICE_ID" },
	{ IOCTL_PAR_SET_INFORMATION, "IOCTL_PAR_SET_INFORMATION" },
	{ IOCTL_PAR_SET_READ_ADDRESS, "IOCTL_PAR_SET_READ_ADDRESS" },
	{ IOCTL_PAR_SET_WRITE_ADDRESS, "IOCTL_PAR_SET_WRITE_ADDRESS" },
	{ IOCTL_PAR_TEST, "IOCTL_PAR_TEST" },
	{ IOCTL_PCMCIA_BASE, "IOCTL_PCMCIA_BASE" },
	{ IOCTL_PCMCIA_HIDE_DEVICE, "IOCTL_PCMCIA_HIDE_DEVICE" },
	{ IOCTL_PCMCIA_REVEAL_DEVICE, "IOCTL_PCMCIA_REVEAL_DEVICE" },
	{ IOCTL_PF_SET_EXTENSION_POINTER, "IOCTL_PF_SET_EXTENSION_POINTER" },
	{ IOCTL_READ_REGISTERS, "IOCTL_READ_REGISTERS" },
	{ IOCTL_REDIR_QUERY_PATH, "IOCTL_REDIR_QUERY_PATH" },
	{ IOCTL_REDIR_QUERY_PATH_EX, "IOCTL_REDIR_QUERY_PATH_EX" },
	{ IOCTL_RESET_PIPE, "IOCTL_RESET_PIPE" },
	{ IOCTL_SCSI_BASE, "IOCTL_SCSI_BASE" },
	{ IOCTL_SCSI_FREE_DUMP_POINTERS, "IOCTL_SCSI_FREE_DUMP_POINTERS" },
	{ IOCTL_SCSI_GET_ADDRESS, "IOCTL_SCSI_GET_ADDRESS" },
	{ IOCTL_SCSI_GET_CAPABILITIES, "IOCTL_SCSI_GET_CAPABILITIES" },
	{ IOCTL_SCSI_GET_DUMP_POINTERS, "IOCTL_SCSI_GET_DUMP_POINTERS" },
	{ IOCTL_SCSI_GET_INQUIRY_DATA, "IOCTL_SCSI_GET_INQUIRY_DATA" },
	{ IOCTL_SCSI_MINIPORT, "IOCTL_SCSI_MINIPORT" },
	{ IOCTL_SCSI_MINIPORT_NVCACHE, "IOCTL_SCSI_MINIPORT_NVCACHE" },
	{ IOCTL_SCSI_PASS_THROUGH, "IOCTL_SCSI_PASS_THROUGH" },
	{ IOCTL_SCSI_PASS_THROUGH_DIRECT, "IOCTL_SCSI_PASS_THROUGH_DIRECT" },
	{ IOCTL_SCSI_RESCAN_BUS, "IOCTL_SCSI_RESCAN_BUS" },
	{ IOCTL_SCSISCAN_CMD		, "IOCTL_SCSISCAN_CMD		" },
	{ IOCTL_SCSISCAN_GET_INFO, "IOCTL_SCSISCAN_GET_INFO" },
	{ IOCTL_SCSISCAN_LOCKDEVICE, "IOCTL_SCSISCAN_LOCKDEVICE" },
	{ IOCTL_SCSISCAN_SET_TIMEOUT, "IOCTL_SCSISCAN_SET_TIMEOUT" },
	{ IOCTL_SCSISCAN_UNLOCKDEVICE, "IOCTL_SCSISCAN_UNLOCKDEVICE" },
	{ IOCTL_SEND_USB_REQUEST, "IOCTL_SEND_USB_REQUEST" },
	{ IOCTL_SERENUM_EXPOSE_HARDWARE, "IOCTL_SERENUM_EXPOSE_HARDWARE" },
	{ IOCTL_SERENUM_GET_PORT_NAME, "IOCTL_SERENUM_GET_PORT_NAME" },
	{ IOCTL_SERENUM_PORT_DESC, "IOCTL_SERENUM_PORT_DESC" },
	{ IOCTL_SERENUM_REMOVE_HARDWARE, "IOCTL_SERENUM_REMOVE_HARDWARE" },
	{ IOCTL_SERIAL_CLEAR_STATS, "IOCTL_SERIAL_CLEAR_STATS" },
	{ IOCTL_SERIAL_CLR_DTR, "IOCTL_SERIAL_CLR_DTR" },
	{ IOCTL_SERIAL_CLR_RTS, "IOCTL_SERIAL_CLR_RTS" },
	{ IOCTL_SERIAL_CONFIG_SIZE, "IOCTL_SERIAL_CONFIG_SIZE" },
	{ IOCTL_SERIAL_GET_BAUD_RATE, "IOCTL_SERIAL_GET_BAUD_RATE" },
	{ IOCTL_SERIAL_GET_CHARS, "IOCTL_SERIAL_GET_CHARS" },
	{ IOCTL_SERIAL_GET_COMMCONFIG, "IOCTL_SERIAL_GET_COMMCONFIG" },
	{ IOCTL_SERIAL_GET_COMMSTATUS, "IOCTL_SERIAL_GET_COMMSTATUS" },
	{ IOCTL_SERIAL_GET_DTRRTS, "IOCTL_SERIAL_GET_DTRRTS" },
	{ IOCTL_SERIAL_GET_HANDFLOW, "IOCTL_SERIAL_GET_HANDFLOW" },
	{ IOCTL_SERIAL_GET_LINE_CONTROL, "IOCTL_SERIAL_GET_LINE_CONTROL" },
	{ IOCTL_SERIAL_GET_MODEM_CONTROL, "IOCTL_SERIAL_GET_MODEM_CONTROL" },
	{ IOCTL_SERIAL_GET_MODEMSTATUS, "IOCTL_SERIAL_GET_MODEMSTATUS" },
	{ IOCTL_SERIAL_GET_PROPERTIES, "IOCTL_SERIAL_GET_PROPERTIES" },
	{ IOCTL_SERIAL_GET_STATS, "IOCTL_SERIAL_GET_STATS" },
	{ IOCTL_SERIAL_GET_TIMEOUTS, "IOCTL_SERIAL_GET_TIMEOUTS" },
	{ IOCTL_SERIAL_GET_WAIT_MASK, "IOCTL_SERIAL_GET_WAIT_MASK" },
	{ IOCTL_SERIAL_IMMEDIATE_CHAR, "IOCTL_SERIAL_IMMEDIATE_CHAR" },
	{ IOCTL_SERIAL_LSRMST_INSERT, "IOCTL_SERIAL_LSRMST_INSERT" },
	{ IOCTL_SERIAL_PURGE, "IOCTL_SERIAL_PURGE" },
	{ IOCTL_SERIAL_RESET_DEVICE, "IOCTL_SERIAL_RESET_DEVICE" },
	{ IOCTL_SERIAL_SET_BAUD_RATE, "IOCTL_SERIAL_SET_BAUD_RATE" },
	{ IOCTL_SERIAL_SET_BREAK_OFF, "IOCTL_SERIAL_SET_BREAK_OFF" },
	{ IOCTL_SERIAL_SET_BREAK_ON, "IOCTL_SERIAL_SET_BREAK_ON" },
	{ IOCTL_SERIAL_SET_CHARS, "IOCTL_SERIAL_SET_CHARS" },
	{ IOCTL_SERIAL_SET_COMMCONFIG, "IOCTL_SERIAL_SET_COMMCONFIG" },
	{ IOCTL_SERIAL_SET_DTR, "IOCTL_SERIAL_SET_DTR" },
	{ IOCTL_SERIAL_SET_FIFO_CONTROL, "IOCTL_SERIAL_SET_FIFO_CONTROL" },
	{ IOCTL_SERIAL_SET_HANDFLOW, "IOCTL_SERIAL_SET_HANDFLOW" },
	{ IOCTL_SERIAL_SET_LINE_CONTROL, "IOCTL_SERIAL_SET_LINE_CONTROL" },
	{ IOCTL_SERIAL_SET_MODEM_CONTROL, "IOCTL_SERIAL_SET_MODEM_CONTROL" },
	{ IOCTL_SERIAL_SET_QUEUE_SIZE, "IOCTL_SERIAL_SET_QUEUE_SIZE" },
	{ IOCTL_SERIAL_SET_RTS, "IOCTL_SERIAL_SET_RTS" },
	{ IOCTL_SERIAL_SET_TIMEOUTS, "IOCTL_SERIAL_SET_TIMEOUTS" },
	{ IOCTL_SERIAL_SET_WAIT_MASK, "IOCTL_SERIAL_SET_WAIT_MASK" },
	{ IOCTL_SERIAL_SET_XOFF, "IOCTL_SERIAL_SET_XOFF" },
	{ IOCTL_SERIAL_SET_XON, "IOCTL_SERIAL_SET_XON" },
	{ IOCTL_SERIAL_WAIT_ON_MASK, "IOCTL_SERIAL_WAIT_ON_MASK" },
	{ IOCTL_SERIAL_XOFF_COUNTER, "IOCTL_SERIAL_XOFF_COUNTER" },
	{ IOCTL_SET_NUM_DEVICE_INPUT_BUFFERS, "IOCTL_SET_NUM_DEVICE_INPUT_BUFFERS" },
	{ IOCTL_SET_SERVER_STATE, "IOCTL_SET_SERVER_STATE" },
	{ IOCTL_SET_SYS_MESSAGE_INDICATOR, "IOCTL_SET_SYS_MESSAGE_INDICATOR" },
	{ IOCTL_SET_TIMEOUT, "IOCTL_SET_TIMEOUT" },
	{ IOCTL_SFFDISK_DEVICE_COMMAND, "IOCTL_SFFDISK_DEVICE_COMMAND" },
	{ IOCTL_SFFDISK_DEVICE_PASSWORD, "IOCTL_SFFDISK_DEVICE_PASSWORD" },
	{ IOCTL_SFFDISK_QUERY_DEVICE_PROTOCOL, "IOCTL_SFFDISK_QUERY_DEVICE_PROTOCOL" },
	{ IOCTL_SOCKET_INFORMATION, "IOCTL_SOCKET_INFORMATION" },
	{ IOCTL_STORAGE_ALLOCATE_BC_STREAM, "IOCTL_STORAGE_ALLOCATE_BC_STREAM" },
	{ IOCTL_STORAGE_BASE, "IOCTL_STORAGE_BASE" },
	{ IOCTL_STORAGE_BREAK_RESERVATION, "IOCTL_STORAGE_BREAK_RESERVATION" },
	{ IOCTL_STORAGE_CHECK_PRIORITY_HINT_SUPPORT, "IOCTL_STORAGE_CHECK_PRIORITY_HINT_SUPPORT" },
	{ IOCTL_STORAGE_CHECK_VERIFY, "IOCTL_STORAGE_CHECK_VERIFY" },
	{ IOCTL_STORAGE_CHECK_VERIFY2, "IOCTL_STORAGE_CHECK_VERIFY2" },
	{ IOCTL_STORAGE_EJECT_MEDIA, "IOCTL_STORAGE_EJECT_MEDIA" },
	{ IOCTL_STORAGE_EJECTION_CONTROL, "IOCTL_STORAGE_EJECTION_CONTROL" },
	{ IOCTL_STORAGE_FIND_NEW_DEVICES, "IOCTL_STORAGE_FIND_NEW_DEVICES" },
	{ IOCTL_STORAGE_FREE_BC_STREAM, "IOCTL_STORAGE_FREE_BC_STREAM" },
	{ IOCTL_STORAGE_GET_BC_PROPERTIES, "IOCTL_STORAGE_GET_BC_PROPERTIES" },
	{ IOCTL_STORAGE_GET_DEVICE_NUMBER, "IOCTL_STORAGE_GET_DEVICE_NUMBER" },
	{ IOCTL_STORAGE_GET_HOTPLUG_INFO, "IOCTL_STORAGE_GET_HOTPLUG_INFO" },
	{ IOCTL_STORAGE_GET_MEDIA_SERIAL_NUMBER, "IOCTL_STORAGE_GET_MEDIA_SERIAL_NUMBER" },
	{ IOCTL_STORAGE_GET_MEDIA_TYPES, "IOCTL_STORAGE_GET_MEDIA_TYPES" },
	{ IOCTL_STORAGE_GET_MEDIA_TYPES_EX, "IOCTL_STORAGE_GET_MEDIA_TYPES_EX" },
	{ IOCTL_STORAGE_LOAD_MEDIA, "IOCTL_STORAGE_LOAD_MEDIA" },
	{ IOCTL_STORAGE_LOAD_MEDIA2, "IOCTL_STORAGE_LOAD_MEDIA2" },
	{ IOCTL_STORAGE_MCN_CONTROL, "IOCTL_STORAGE_MCN_CONTROL" },
	{ IOCTL_STORAGE_MEDIA_REMOVAL, "IOCTL_STORAGE_MEDIA_REMOVAL" },
	{ IOCTL_STORAGE_PERSISTENT_RESERVE_IN, "IOCTL_STORAGE_PERSISTENT_RESERVE_IN" },
	{ IOCTL_STORAGE_PERSISTENT_RESERVE_OUT, "IOCTL_STORAGE_PERSISTENT_RESERVE_OUT" },
	{ IOCTL_STORAGE_PREDICT_FAILURE, "IOCTL_STORAGE_PREDICT_FAILURE" },
	{ IOCTL_STORAGE_QUERY_PROPERTY, "IOCTL_STORAGE_QUERY_PROPERTY" },
	{ IOCTL_STORAGE_READ_CAPACITY, "IOCTL_STORAGE_READ_CAPACITY" },
	{ IOCTL_STORAGE_RELEASE, "IOCTL_STORAGE_RELEASE" },
	{ IOCTL_STORAGE_RESERVE, "IOCTL_STORAGE_RESERVE" },
	{ IOCTL_STORAGE_RESET_BUS, "IOCTL_STORAGE_RESET_BUS" },
	{ IOCTL_STORAGE_RESET_DEVICE, "IOCTL_STORAGE_RESET_DEVICE" },
	{ IOCTL_STORAGE_SET_HOTPLUG_INFO, "IOCTL_STORAGE_SET_HOTPLUG_INFO" },
	{ IOCTL_STORAGE_SET_READ_AHEAD, "IOCTL_STORAGE_SET_READ_AHEAD" },
	{ IOCTL_TAPE_BASE, "IOCTL_TAPE_BASE" },
	{ IOCTL_TAPE_CREATE_PARTITION, "IOCTL_TAPE_CREATE_PARTITION" },
	{ IOCTL_TAPE_EJECT_MEDIA, "IOCTL_TAPE_EJECT_MEDIA" },
	{ IOCTL_TAPE_ERASE, "IOCTL_TAPE_ERASE" },
	{ IOCTL_TAPE_GET_DRIVE_PARAMS, "IOCTL_TAPE_GET_DRIVE_PARAMS" },
	{ IOCTL_TAPE_GET_MEDIA_PARAMS, "IOCTL_TAPE_GET_MEDIA_PARAMS" },
	{ IOCTL_TAPE_GET_POSITION, "IOCTL_TAPE_GET_POSITION" },
	{ IOCTL_TAPE_GET_STATUS, "IOCTL_TAPE_GET_STATUS" },
	{ IOCTL_TAPE_LOAD_MEDIA, "IOCTL_TAPE_LOAD_MEDIA" },
	{ IOCTL_TAPE_MEDIA_REMOVAL, "IOCTL_TAPE_MEDIA_REMOVAL" },
	{ IOCTL_TAPE_PREPARE, "IOCTL_TAPE_PREPARE" },
	{ IOCTL_TAPE_RELEASE, "IOCTL_TAPE_RELEASE" },
	{ IOCTL_TAPE_RESERVE, "IOCTL_TAPE_RESERVE" },
	{ IOCTL_TAPE_SET_DRIVE_PARAMS, "IOCTL_TAPE_SET_DRIVE_PARAMS" },
	{ IOCTL_TAPE_SET_MEDIA_PARAMS, "IOCTL_TAPE_SET_MEDIA_PARAMS" },
	{ IOCTL_TAPE_SET_POSITION, "IOCTL_TAPE_SET_POSITION" },
	{ IOCTL_TAPE_WRITE_MARKS, "IOCTL_TAPE_WRITE_MARKS" },
	{ IOCTL_TDI_ACCEPT, "IOCTL_TDI_ACCEPT" },
	{ IOCTL_TDI_ACTION, "IOCTL_TDI_ACTION" },
	{ IOCTL_TDI_ASSOCIATE_ADDRESS, "IOCTL_TDI_ASSOCIATE_ADDRESS" },
	{ IOCTL_TDI_CONNECT, "IOCTL_TDI_CONNECT" },
	{ IOCTL_TDI_DISASSOCIATE_ADDRESS, "IOCTL_TDI_DISASSOCIATE_ADDRESS" },
	{ IOCTL_TDI_DISCONNECT, "IOCTL_TDI_DISCONNECT" },
	{ IOCTL_TDI_LISTEN, "IOCTL_TDI_LISTEN" },
	{ IOCTL_TDI_MAGIC_BULLET, "IOCTL_TDI_MAGIC_BULLET" },
	{ IOCTL_TDI_QUERY_DIRECT_SEND_HANDLER, "IOCTL_TDI_QUERY_DIRECT_SEND_HANDLER" },
	{ IOCTL_TDI_QUERY_DIRECT_SENDDG_HANDLER, "IOCTL_TDI_QUERY_DIRECT_SENDDG_HANDLER" },
	{ IOCTL_TDI_QUERY_INFORMATION, "IOCTL_TDI_QUERY_INFORMATION" },
	{ IOCTL_TDI_RECEIVE, "IOCTL_TDI_RECEIVE" },
	{ IOCTL_TDI_RECEIVE_DATAGRAM, "IOCTL_TDI_RECEIVE_DATAGRAM" },
	{ IOCTL_TDI_SEND, "IOCTL_TDI_SEND" },
	{ IOCTL_TDI_SEND_DATAGRAM, "IOCTL_TDI_SEND_DATAGRAM" },
	{ IOCTL_TDI_SET_EVENT_HANDLER, "IOCTL_TDI_SET_EVENT_HANDLER" },
	{ IOCTL_TDI_SET_INFORMATION, "IOCTL_TDI_SET_INFORMATION" },
	{ IOCTL_TDI_TL_IO_CONTROL_ENDPOINT, "IOCTL_TDI_TL_IO_CONTROL_ENDPOINT" },
	{ IOCTL_THERMAL_QUERY_INFORMATION, "IOCTL_THERMAL_QUERY_INFORMATION" },
	{ IOCTL_USB_DIAGNOSTIC_MODE_OFF, "IOCTL_USB_DIAGNOSTIC_MODE_OFF" },
	{ IOCTL_USB_DIAGNOSTIC_MODE_ON, "IOCTL_USB_DIAGNOSTIC_MODE_ON" },
	{ IOCTL_USB_GET_ROOT_HUB_NAME, "IOCTL_USB_GET_ROOT_HUB_NAME" },
	{ IOCTL_USB_HCD_DISABLE_PORT, "IOCTL_USB_HCD_DISABLE_PORT" },
	{ IOCTL_USB_HCD_ENABLE_PORT, "IOCTL_USB_HCD_ENABLE_PORT" },
	{ IOCTL_USB_HCD_GET_STATS_1, "IOCTL_USB_HCD_GET_STATS_1" },
	{ IOCTL_USB_HCD_GET_STATS_2, "IOCTL_USB_HCD_GET_STATS_2" },
	{ IOCTL_USB_USER_REQUEST, "IOCTL_USB_USER_REQUEST" },
	{ IOCTL_USBPRINT_GET_1284_ID, "IOCTL_USBPRINT_GET_1284_ID" },
	{ IOCTL_USBPRINT_GET_LPT_STATUS, "IOCTL_USBPRINT_GET_LPT_STATUS" },
	{ IOCTL_USBPRINT_SOFT_RESET, "IOCTL_USBPRINT_SOFT_RESET" },
	{ IOCTL_USBPRINT_VENDOR_GET_COMMAND, "IOCTL_USBPRINT_VENDOR_GET_COMMAND" },
	{ IOCTL_USBPRINT_VENDOR_SET_COMMAND, "IOCTL_USBPRINT_VENDOR_SET_COMMAND" },
	{ IOCTL_VIDEO_DISABLE_CURSOR, "IOCTL_VIDEO_DISABLE_CURSOR" },
	{ IOCTL_VIDEO_DISABLE_POINTER, "IOCTL_VIDEO_DISABLE_POINTER" },
	{ IOCTL_VIDEO_DISABLE_VDM, "IOCTL_VIDEO_DISABLE_VDM" },
	{ IOCTL_VIDEO_ENABLE_CURSOR, "IOCTL_VIDEO_ENABLE_CURSOR" },
	{ IOCTL_VIDEO_ENABLE_POINTER, "IOCTL_VIDEO_ENABLE_POINTER" },
	{ IOCTL_VIDEO_ENUM_MONITOR_PDO, "IOCTL_VIDEO_ENUM_MONITOR_PDO" },
	{ IOCTL_VIDEO_FREE_PUBLIC_ACCESS_RANGES, "IOCTL_VIDEO_FREE_PUBLIC_ACCESS_RANGES" },
	{ IOCTL_VIDEO_GET_BANK_SELECT_CODE, "IOCTL_VIDEO_GET_BANK_SELECT_CODE" },
	{ IOCTL_VIDEO_GET_CHILD_STATE, "IOCTL_VIDEO_GET_CHILD_STATE" },
	{ IOCTL_VIDEO_GET_OUTPUT_DEVICE_POWER_STATE, "IOCTL_VIDEO_GET_OUTPUT_DEVICE_POWER_STATE" },
	{ IOCTL_VIDEO_GET_POWER_MANAGEMENT, "IOCTL_VIDEO_GET_POWER_MANAGEMENT" },
	{ IOCTL_VIDEO_HANDLE_VIDEOPARAMETERS, "IOCTL_VIDEO_HANDLE_VIDEOPARAMETERS" },
	{ IOCTL_VIDEO_INIT_WIN32K_CALLBACKS, "IOCTL_VIDEO_INIT_WIN32K_CALLBACKS" },
	{ IOCTL_VIDEO_IS_VGA_DEVICE, "IOCTL_VIDEO_IS_VGA_DEVICE" },
	{ IOCTL_VIDEO_LOAD_AND_SET_FONT, "IOCTL_VIDEO_LOAD_AND_SET_FONT" },
	{ IOCTL_VIDEO_MAP_VIDEO_MEMORY, "IOCTL_VIDEO_MAP_VIDEO_MEMORY" },
	{ IOCTL_VIDEO_MONITOR_DEVICE, "IOCTL_VIDEO_MONITOR_DEVICE" },
	{ IOCTL_VIDEO_PREPARE_FOR_EARECOVERY, "IOCTL_VIDEO_PREPARE_FOR_EARECOVERY" },
	{ IOCTL_VIDEO_QUERY_AVAIL_MODES, "IOCTL_VIDEO_QUERY_AVAIL_MODES" },
	{ IOCTL_VIDEO_QUERY_COLOR_CAPABILITIES, "IOCTL_VIDEO_QUERY_COLOR_CAPABILITIES" },
	{ IOCTL_VIDEO_QUERY_CURRENT_MODE, "IOCTL_VIDEO_QUERY_CURRENT_MODE" },
	{ IOCTL_VIDEO_QUERY_CURSOR_ATTR, "IOCTL_VIDEO_QUERY_CURSOR_ATTR" },
	{ IOCTL_VIDEO_QUERY_CURSOR_POSITION, "IOCTL_VIDEO_QUERY_CURSOR_POSITION" },
	{ IOCTL_VIDEO_QUERY_DISPLAY_BRIGHTNESS, "IOCTL_VIDEO_QUERY_DISPLAY_BRIGHTNESS" },
	{ IOCTL_VIDEO_QUERY_NUM_AVAIL_MODES, "IOCTL_VIDEO_QUERY_NUM_AVAIL_MODES" },
	{ IOCTL_VIDEO_QUERY_POINTER_ATTR, "IOCTL_VIDEO_QUERY_POINTER_ATTR" },
	{ IOCTL_VIDEO_QUERY_POINTER_CAPABILITIES, "IOCTL_VIDEO_QUERY_POINTER_CAPABILITIES" },
	{ IOCTL_VIDEO_QUERY_POINTER_POSITION, "IOCTL_VIDEO_QUERY_POINTER_POSITION" },
	{ IOCTL_VIDEO_QUERY_PUBLIC_ACCESS_RANGES, "IOCTL_VIDEO_QUERY_PUBLIC_ACCESS_RANGES" },
	{ IOCTL_VIDEO_QUERY_SUPPORTED_BRIGHTNESS, "IOCTL_VIDEO_QUERY_SUPPORTED_BRIGHTNESS" },
	{ IOCTL_VIDEO_REGISTER_VDM, "IOCTL_VIDEO_REGISTER_VDM" },
	{ IOCTL_VIDEO_RESET_DEVICE, "IOCTL_VIDEO_RESET_DEVICE" },
	{ IOCTL_VIDEO_SET_BANK_POSITION, "IOCTL_VIDEO_SET_BANK_POSITION" },
	{ IOCTL_VIDEO_SET_CHILD_STATE_CONFIGURATION, "IOCTL_VIDEO_SET_CHILD_STATE_CONFIGURATION" },
	{ IOCTL_VIDEO_SET_COLOR_LUT_DATA, "IOCTL_VIDEO_SET_COLOR_LUT_DATA" },
	{ IOCTL_VIDEO_SET_COLOR_REGISTERS, "IOCTL_VIDEO_SET_COLOR_REGISTERS" },
	{ IOCTL_VIDEO_SET_CURRENT_MODE, "IOCTL_VIDEO_SET_CURRENT_MODE" },
	{ IOCTL_VIDEO_SET_CURSOR_ATTR, "IOCTL_VIDEO_SET_CURSOR_ATTR" },
	{ IOCTL_VIDEO_SET_CURSOR_POSITION, "IOCTL_VIDEO_SET_CURSOR_POSITION" },
	{ IOCTL_VIDEO_SET_DISPLAY_BRIGHTNESS, "IOCTL_VIDEO_SET_DISPLAY_BRIGHTNESS" },
	{ IOCTL_VIDEO_SET_OUTPUT_DEVICE_POWER_STATE, "IOCTL_VIDEO_SET_OUTPUT_DEVICE_POWER_STATE" },
	{ IOCTL_VIDEO_SET_PALETTE_REGISTERS, "IOCTL_VIDEO_SET_PALETTE_REGISTERS" },
	{ IOCTL_VIDEO_SET_POINTER_ATTR, "IOCTL_VIDEO_SET_POINTER_ATTR" },
	{ IOCTL_VIDEO_SET_POINTER_POSITION, "IOCTL_VIDEO_SET_POINTER_POSITION" },
	{ IOCTL_VIDEO_SET_POWER_MANAGEMENT, "IOCTL_VIDEO_SET_POWER_MANAGEMENT" },
	{ IOCTL_VIDEO_SHARE_VIDEO_MEMORY, "IOCTL_VIDEO_SHARE_VIDEO_MEMORY" },
	{ IOCTL_VIDEO_SWITCH_DUALVIEW, "IOCTL_VIDEO_SWITCH_DUALVIEW" },
	{ IOCTL_VIDEO_UNMAP_VIDEO_MEMORY, "IOCTL_VIDEO_UNMAP_VIDEO_MEMORY" },
	{ IOCTL_VIDEO_UNSHARE_VIDEO_MEMORY, "IOCTL_VIDEO_UNSHARE_VIDEO_MEMORY" },
	{ IOCTL_VIDEO_USE_DEVICE_IN_SESSION, "IOCTL_VIDEO_USE_DEVICE_IN_SESSION" },
	{ IOCTL_VIDEO_VALIDATE_CHILD_STATE_CONFIGURATION, "IOCTL_VIDEO_VALIDATE_CHILD_STATE_CONFIGURATION" },
	{ IOCTL_VOLSNAP_FLUSH_AND_HOLD_WRITES, "IOCTL_VOLSNAP_FLUSH_AND_HOLD_WRITES" },
	{ IOCTL_VOLUME_ALLOCATE_BC_STREAM, "IOCTL_VOLUME_ALLOCATE_BC_STREAM" },
	{ IOCTL_VOLUME_BASE, "IOCTL_VOLUME_BASE" },
	{ IOCTL_VOLUME_BC_VERSION, "IOCTL_VOLUME_BC_VERSION" },
	{ IOCTL_VOLUME_FREE_BC_STREAM, "IOCTL_VOLUME_FREE_BC_STREAM" },
	{ IOCTL_VOLUME_GET_BC_PROPERTIES, "IOCTL_VOLUME_GET_BC_PROPERTIES" },
	{ IOCTL_VOLUME_GET_GPT_ATTRIBUTES, "IOCTL_VOLUME_GET_GPT_ATTRIBUTES" },
	{ IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS, "IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS" },
	{ IOCTL_VOLUME_IS_CLUSTERED, "IOCTL_VOLUME_IS_CLUSTERED" },
	{ IOCTL_VOLUME_IS_DYNAMIC, "IOCTL_VOLUME_IS_DYNAMIC" },
	{ IOCTL_VOLUME_IS_IO_CAPABLE, "IOCTL_VOLUME_IS_IO_CAPABLE" },
	{ IOCTL_VOLUME_IS_OFFLINE, "IOCTL_VOLUME_IS_OFFLINE" },
	{ IOCTL_VOLUME_IS_PARTITION, "IOCTL_VOLUME_IS_PARTITION" },
	{ IOCTL_VOLUME_LOGICAL_TO_PHYSICAL, "IOCTL_VOLUME_LOGICAL_TO_PHYSICAL" },
	{ IOCTL_VOLUME_OFFLINE, "IOCTL_VOLUME_OFFLINE" },
	{ IOCTL_VOLUME_ONLINE, "IOCTL_VOLUME_ONLINE" },
	{ IOCTL_VOLUME_PHYSICAL_TO_LOGICAL, "IOCTL_VOLUME_PHYSICAL_TO_LOGICAL" },
	{ IOCTL_VOLUME_PREPARE_FOR_CRITICAL_IO, "IOCTL_VOLUME_PREPARE_FOR_CRITICAL_IO" },
	{ IOCTL_VOLUME_PREPARE_FOR_SHRINK, "IOCTL_VOLUME_PREPARE_FOR_SHRINK" },
	{ IOCTL_VOLUME_QUERY_ALLOCATION_HINT, "IOCTL_VOLUME_QUERY_ALLOCATION_HINT" },
	{ IOCTL_VOLUME_QUERY_FAILOVER_SET, "IOCTL_VOLUME_QUERY_FAILOVER_SET" },
	{ IOCTL_VOLUME_QUERY_MINIMUM_SHRINK_SIZE, "IOCTL_VOLUME_QUERY_MINIMUM_SHRINK_SIZE" },
	{ IOCTL_VOLUME_QUERY_VOLUME_NUMBER, "IOCTL_VOLUME_QUERY_VOLUME_NUMBER" },
	{ IOCTL_VOLUME_READ_PLEX, "IOCTL_VOLUME_READ_PLEX" },
	{ IOCTL_VOLUME_SET_GPT_ATTRIBUTES, "IOCTL_VOLUME_SET_GPT_ATTRIBUTES" },
	{ IOCTL_VOLUME_SUPPORTS_ONLINE_OFFLINE, "IOCTL_VOLUME_SUPPORTS_ONLINE_OFFLINE" },
	{ IOCTL_VOLUME_UPDATE_PROPERTIES, "IOCTL_VOLUME_UPDATE_PROPERTIES" },
	{ IOCTL_WAIT_ON_DEVICE_EVENT, "IOCTL_WAIT_ON_DEVICE_EVENT" },
	{ IOCTL_WRITE_REGISTERS, "IOCTL_WRITE_REGISTERS" }
};

void dbg_ioctl_print(u32 ioctl)
{
	char *res = NULL;
	int   i;

	for (i = 0; i < sizeof(ioctl_table) / sizeof(ioctl_table[0]); i++) {
		if (ioctl_table[i].code == ioctl) {
			res = ioctl_table[i].name;
			break;
		}
	}

	if (res != NULL) {
		DbgMsg("IOCTL: %s\n", res);
	} else {
		DbgMsg("IOCTL: %0.8x\n", ioctl);
	}
}

#ifdef DBG_FILE
void debug_out(char *format, ...)
{
	OBJECT_ATTRIBUTES         obj;
	UNICODE_STRING            u_name;
	IO_STATUS_BLOCK           io_status;
	FILE_STANDARD_INFORMATION info = {0};
	FILE_POSITION_INFORMATION pos;
	HANDLE                    h_file = NULL;
	char                      dbg_msg[MAX_PATH];
	va_list                   args;

	va_start(args, format);

	_vsnprintf(
		dbg_msg, 
		sizeof(dbg_msg), 
		format, 
		args
		);

	va_end(args);

	strcat(dbg_msg, "\xD\xA");

	RtlInitUnicodeString(
		&u_name, 
		L"\\??\\c:\\debug.log"
		);

	InitializeObjectAttributes(
		&obj, 
		&u_name, 
		OBJ_CASE_INSENSITIVE | OBJ_KERNEL_HANDLE, 
		NULL, 
		NULL
		);

	ZwCreateFile(
		&h_file,
		GENERIC_WRITE,
		&obj,
		&io_status,
		NULL, 
		FILE_ATTRIBUTE_NORMAL,
		FILE_SHARE_READ | FILE_SHARE_WRITE,
		FILE_OPEN_IF,
		FILE_SYNCHRONOUS_IO_NONALERT,
		NULL,
		0
		);

	if (h_file != NULL)
	{
		ZwQueryInformationFile(
			h_file, 
			&io_status,
			&info, 
			sizeof(FILE_STANDARD_INFORMATION),
			FileStandardInformation
			);

		pos.CurrentByteOffset = info.EndOfFile;

		ZwSetInformationFile(
			h_file, 
			&io_status,
			&pos, 
			sizeof(FILE_POSITION_INFORMATION),
			FilePositionInformation
			);

		ZwWriteFile(
			h_file,
			NULL,
			NULL,
			NULL,
			&io_status,
			dbg_msg,
			strlen(dbg_msg),
			NULL,
			NULL
			);

		ZwClose(h_file);
	}
}
#endif

#endif